distributable:
  url: https://ftp.gnu.org/gnu/binutils/binutils-{{ version.raw }}.tar.xz
  strip-components: 1

versions:
  #TODO HTML listing: https://ftp.gnu.org/gnu/binutils/
  - '2.40'
  - 2.39

build:
  dependencies:
    tea.xyz/gx/make: '*'
    gnu.org/bison: '*'
    gnu.org/texinfo: '*'
    darwin:
      tea.xyz/gx/cc: c99
    linux:
      gnu.org/gcc: '*'
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }}
    make install
  env:
    ARGS:
      - --prefix={{ prefix }}
      - --enable-gold
      - --enable-ld=default
      - --enable-plugins
      - --enable-shared
      - --disable-werror
    linux:
      ARGS:
        - --enable-64-bit-bfd

test:
  script: objdump -x $(which objdump) | grep -s $TEST_STRING
  env:
    # Representitive output to look for
    darwin:
      TEST_STRING: _opendir
    linux:
      TEST_STRING: GNU_HASH

provides:
  - bin/addr2line
  - bin/ar
  - bin/c++filt
  - bin/elfedit
  - bin/nm
  - bin/objcopy
  - bin/objdump
  - bin/ranlib
  - bin/readelf
  - bin/size
  - bin/strings
  - bin/strip
